export const nameList = [
  "Jace Beleren",
  "Chandra Nalaar",
  "Liliana Vess",
  "Nicol Bolas",
  "Teferi",
  "Garruk Wildspeaker",
  "Ajani Goldmane",
  "Sorin Markov",
  "Karn",
  "Nissa Revane",
  "Elspeth Tirel",
  "Urza",
  "Yawgmoth",
  "Mishra",
  "Serra",
  "Freyalise",
  "Gideon Jura",
  "Tamiyo",
  "Vraska",
  "Ral Zarek",
  "Domri Rade",
  "Narset",
  "Ob Nixilis",
  "Ashiok",
  "Kaya",
  "Nahiri",
  "Saheeli Rai",
  "Dack Fayden",
  "Tibalt",
  "Aminatou",
  "Estrid",
  "Will Kenrith",
  "Rowan Kenrith",
  "Sisay",
  "Teysa Karlov",
  "Queen Marchesa",
  "The Raven Man",
  "Gix",
  "Sheoldred",
  "Elesh Norn",
  "Jin-Gitaxias",
  "Urabrask",
  "Vorinclex",
  "Koth",
  "Venser",
  "Baral",
  "Borborygmos",
  "Lazav",
  "Brimaz",
  "Ezuri",
  "John",
  "Timmy",
  "Johnny",
  "Spike",
  "Vorthos",
];